apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-robot
  name: flask-robot
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-robot
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-robot
    spec:
      containers:
      - image: 82mtanveer/myrepo:flask-robot-led-arm64
        imagePullPolicy: Never
        name: myrepo
        resources: {}
status: {}
