apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: flask-robot-staging:/Service:map[name:staging]/flask-robot
  labels:
    app: flask-robot
  name: flask-robot
  namespace: map[name:staging]
spec:
  ports:
    - name: http
      port: 5002
      protocol: TCP
      targetPort: 5002
  selector:
    app: flask-robot
  type: ClusterIP
