apiVersion: v1
kind: Service
metadata:
  name: flask-robot
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: flask-robot
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 5002 }}
      targetPort: {{ .Values.service.targetPort | default 5002 }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: http
  selector:
    app: flask-robot