namespace:
  name: staging

service:
  port: 5002
  targetPort: 5002
  protocol: TCP
  type: ClusterIP

image:
  repository: 82mtanveer/myrepo
  tag: flask-robot_v1   # ← CHANGE THIS LINE
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

ports:
  containerPort: 5002
  protocol: TCP